Insert into locations (name) values ('Location 1');
Insert into locations (name) values ('Location 2');
Insert into locations (name) values ('Location 3');
Insert into locations (name) values ('Location 4');
Insert into locations (name) values ('Location 5');
Insert into locations (name) values ('Location 6');
select * from locations;
--delete from locations where id > 6;
Insert into BoomSticks (Consumed, species) values ( 0, 'Fir');
Insert into BoomSticks (Consumed, species) values ( 0, 'Fir');
Insert into BoomSticks (Consumed, species) values ( 0, 'Fir');
Insert into BoomSticks (Consumed, species) values ( 0, 'Fir');
Insert into BoomSticks (Consumed, species) values ( 0, 'Fir');
Insert into BoomSticks (Consumed, species) values ( 0, 'Fir');
Insert into BoomSticks (Consumed, species) values ( 0, 'Fir');
select * from BoomSticks;
insert into booms (Location_Id, IsActive) values (1,1);
insert into booms (Location_Id, IsActive) values (1,1);
insert into booms (Location_Id, IsActive) values (2,1);
insert into booms (Location_Id, IsActive) values (3,1);
insert into booms (Location_Id, IsActive) values (3,1);
select * from booms;
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Cedar', 50.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Fir', 65.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
insert into logs (Species, Volume, Consumed) values ('Hemlock', 75.0, 0);
select * from logs;
Insert into BoomGears (Description) values ('Gear 1');
Insert into BoomGears (Description) values ('Gear 2');
Insert into BoomGears (Description) values ('Gear 3');
Insert into BoomGears (Description) values ('Gear 4');
Insert into BoomGears (Description) values ('Gear 5');
Insert into BoomGears (Description) values ('Gear 6');
Insert into BoomGears (Description) values ('Gear 7');
select * from BoomGears;

